### ISSUE TITLE
Feature: Add Missing Visits KRI

### ISSUE THREAD

**Issue by mattroumaya** [Gilead-BioStats/gsm#1488]
## Feature Details

**KRI Description:**
- Numerator: Expected visits to date (actual)
- Denominator: Total expected visits to date
- Source Data: RAVE
  - We need to define a data specification for the raw data, then;
  - Write a mapping function for the numerator + denominator

---

- [ ] Define data specification for the raw data input(s)
- [ ] Write a mapping function for the numerator + denominator
- [ ] Define data specification for the output of a mapping function
- [ ] Define what _missing visit_ means/how it is derived

Add to `inst/mappings/mapping_edc.yaml`:

```
dfVISIT:
  strStudyCol:
  strIDCol:
  strVisitCol:
  strActualVisitDateCol:
  strExpectedVisitDateStartCol:
  strExpectedVisitDateEndCol:
  strUnscheduledVisitCol: 
  strUnscheduledVisitVal:
    - "reason1"
    - "reason2"
```

Will also need to add a spec to [`inst/specs/*_Map_Raw.yaml`](https://github.com/Gilead-BioStats/gsm/tree/dev/inst/specs)
