### ISSUE TITLE
add KRI distribution reporting

### ISSUE THREAD

**Issue by andersonjake1988** [Gilead-BioStats/gsm#1494]
Add reporting like the Discontinuation Report, for KRI's highlighting distribution of causes

**Comment by andersonjake1988** [comment]
dfSUBJ can't join to dfQUERY (kri0009), dfDATAENT (kri0010), or dfDATACHG (kri0011) because subjectname found in these 3 don't match format of subjectid of dfSUBJ, unable to get site.

**Comment by jwildfire** [comment]
@mattroumaya @andersonjake1988 

After thinking some more, I recommend adding a new `config` element in our yaml workflows to capture the covariates for each KRI.  Something like this: 

```
name: AE
config: 
   covariates: 
      - domain: dfAE
         column: strSystemOrganClassCol 
      - domain: dfAE
         column: strSeriousCol
steps:
  - name: FilterDomain
    inputs: dfSUBJ
    output: dfSUBJ
    params:
      strDomain: dfSUBJ
      strColParam: strEnrollCol
      strValParam: strEnrollVal
```

This approach may have some other side benefits for other upcoming reports, that may need additional covariates/config that aren't tied to a specific function.
