### ISSUE TITLE
Feature: Document thresholds in `meta` section of workflows

### ISSUE THREAD

**Issue by jwildfire** [Gilead-BioStats/gsm#1542]
## Feature Details
Document thresholds in workflow headers instead instead of in workflow.

## Example Code

```
meta:
  file: ae.yaml
  workflowid: kri0001
  group: site
  abbreviation: AE
  metric: Adverse Event Rate
  numerator: Adverse Events
  denominator: Days on Study
  model: Normal Approximation
  score: Adjusted Z-Score
  threshold:
    - -2
    - -1
    - 2
    - 3
```
## Possible Implementation
There are a few details to sort out: 
- Need to figure out if updates are needed in `RunStep` to implement ... 
- How does the threshold array translate to the `dfMetrics` data frame. 
- Update charts to pull threshold info from `dfMetrics` instead of `dfBounds` or `workflow$steps`

**Comment by jwildfire** [comment]
Maybe we actually just name each threshold instead of using an array. Would simplify mapping to `dfMetrics`, but not quite as generalizable ... Something like:  

```
meta:
  file: ae.yaml
  workflowid: kri0001
  group: site
  abbreviation: AE
  metric: Adverse Event Rate
  numerator: Adverse Events
  denominator: Days on Study
  model: Normal Approximation
  score: Adjusted Z-Score
  threshold_low_red: -2
  threshold_low_amber: -1
  threshold_high_amber: 1
  threshold_high_red: 3
```

@samussiah any thoughts?
