### ISSUE TITLE
Feature: Add nMinDenominator parameter to `Summarize` step in yaml workflows

### ISSUE THREAD

**Issue by lauramaxwell** [Gilead-BioStats/gsm#1568]
## Feature Details

Add nMinDenominator parameter to `Summarize` step in yaml workflows

## Example Code

Add param to the step (see below) and add an `nMinDenominator` parameter to the meta section of each yaml file
```
  - name: Summarize
    output: dfSummary
    params: 
      dfFlagged: dfFlagged
      nMinDenominator: nMinDenominator
```
