### ISSUE TITLE
QC: Update Articles dropdown in pkgdown header

### ISSUE THREAD

**Issue by jwildfire** [Gilead-BioStats/gsm#1760]
## QC Details
Let's add an [`articles` section to `_pkgdown.yml`](https://pkgdown.r-lib.org/reference/build_articles.html#index-and-navbar)

- Include the following in the pkgdown header dropdown (others can be accessed via articles page): 
  - Data Model Overview (DataModel.rmd)
  - Analysis Pipeline Deep Dive (DataAnalysis.rmd)
  - Reporting Pipeline Deep Dive (DataReporting.rmd)
  - Cookbook (Cookbook.rmd)

**Comment by jwildfire** [comment]
Something like this: 
```
articles: 
  - title: "Data Model"
    navbar: ~
    contents: 
      - DataModel
      - Cookbook
      - DataAnalysis
      - DataReporting
      - KRI Methods
  - title: "Quality"
    navbar: ~ 
    contents: 
      - QualificationWorkflow
      - Qualification
      - ContributorGuidelines
```
