### ISSUE TITLE
Feature: Support optional filter expressions in `Input_Rate()`

### ISSUE THREAD

**Issue by jwildfire** [Gilead-BioStats/gsm#1784]
## Feature Details
Optionally allow users to provide expressions that will filter the input data frames (dfSubject, dfNumerator, dfDenominator) in `input_rate()`. 

The yaml version of the SAE KRI might become something like: 

```
- name: Input_Rate
    output: Analysis_Input
    params:
      dfSubjects: Mapped_DM # was Mapped_Enrolled
      dfNumerator: Mapped_AE # was Mapped_SAE
      dfDenominator: Mapped_DM # previously Mapped_Enrolled
      expFilterSubjects: enrollyn == 'Y'
      expFilterNumerator: aeser == 'Y'
      expFilterDenominator: enrollyn == 'Y'
      strSubjectCol: subjid
      strGroupCol: country
      strGroupLevel: GroupLevel
      strNumeratorMethod: Count
      strDenominatorMethod: Sum
      strDenominatorCol: timeonstudy
```

This should reduce the number of needed data domains in the Mapped data.
