### ISSUE TITLE
QC: Reconsider use of `_all` in yaml specs

### ISSUE THREAD

**Issue by lauramaxwell** [Gilead-BioStats/gsm#1952]
## QC Details

Currently, in all phases of the pipeline after `1_mapping`, we allow for a user to specify that they want `_all` columns of a given data.frame to be required for that yaml workflow. As it is, this can be specified simply, like so:
```
spec:
   Reporting_Results:
    _all:
      required: true
```
Or in conjunction with a subset of columns that the user wants to specify the type of, for validation purposes, like below:
```
spec:
   Reporting_Results:
    _all:
      required: true
    Numerator:
      type: numeric
    Denominator:
      type: numeric
```

In #1936, we remove the `required` field in `spec`, so this brings up the question of how to specify that we want all columns in a data.frame to be passed in without losing functionality or causing major disruption to the expected structure of the spec object (list of lists).

One way to do this would simply to remove the `required` field in `_all` and just specify that `_all` is true, like below:
```
spec:
   Reporting_Results:
    _all: true
```
or
```
spec:
   Reporting_Results:
    _all: true
    Numerator:
      type: numeric
    Denominator:
      type: numeric
```

Alternatively, we can remove the `type` specification of any data.frame that we want to bring in `all` columns of, and simply specify:
```
spec:
   Reporting_Results: true
```
This second option may have negative consequences for ensuring columns maintain the correct type throughout the full pipeline, especially if there is a possibility that intermediate files are saved out and brought back into the R session.

The final option is to not include `specs` in report workflows at all, since they always take in data.frames/objects that have been passed through a spec'd out workflow, so they should theoretically have everything needed for the report. However, this makes it harder to track dependencies between workflows.

**Comment by lauramaxwell** [comment]
@jwildfire @dpastoor @jonthegeek @samussiah - thoughts?

**Comment by lauramaxwell** [comment]
Another option would be:
```
spec:
   Reporting_Results:
    required: true
```

**Comment by jonthegeek** [comment]
I have several specs that look similar to this in {gsm.app}. I currently use them to translate clindata into sample data, but I imagined using something similar to help people translate their data to what we use/display:

```yaml
meta:
  Type: User
  ID: AdverseEvents
  Description: Adverse Event User-Facing Data
  Priority: 1
spec:
  Raw_AE:
    SubjectID:
      required: true
      type: character
      source_col: subjid
    serious:
      required: true
      type: character
      source_col: aeser
    start_date:
      required: false
      type: Date
      source_col: aest_dt
    end_date:
      required: false
      type: Date
      source_col: aeen_dt
    preferred_term:
      required: false
      type: character
      source_col: mdrpt_nsv
    system_organ_class:
      required: false
      type: character
      source_col: mdrsoc_nsv
    toxicity_grade:
      required: false
      type: character
      source_col: aetoxgr
steps:
  - output: User_AE
    name: =
    params:
      lhs: User_AE
      rhs: Raw_AE
```

All the `required: false` entries are because those are nice, and we'll (eventually) offer deeper dives when those columns are available, but nothing will *break* if they're not there. The impression I'm getting is that we don't want to use workflows for that, so I should probably just write normal R code to do this stuff. I don't think I fully understand what workflows are intended to be used for, though.

For the immediate discussion... I don't think any of the things that are planned make sense for how I envisioned using workflows, so I don't have a strong opinion about which way it would be least confusing to indicate the requirements.

**Comment by jwildfire** [comment]
I'm leaning towards moving to this format for the specs in a future release. I think this would largely remove the need for the `_all` keyword. 

```
spec: 
    - domain: mapping
.     table: labs
    - domain: mapping
      table: ae
      columns: 
       - name: SubjectID:
         type: character
         source_col: subjid
       - name: serious
         required: true
         type: character
         source_col: aeser    
```
