### ISSUE TITLE
fix missing lData passthrough for Loading hook

### ISSUE THREAD

**Issue by dpastoor** [Gilead-BioStats/gsm#1981]
## Expected Behavior
lData should be available

## Current Behavior
objects saved in lData are not available

This generally isn't seen for many of the processing elements as most use derived components that come from the various processing layers. The place this emerged was when calling MakeMetric, which takes an lWorkflows object. To get this to pass through the full RunWorkflows function.

A snippet of what this looks like:

The Metrics.yaml of:

```
meta:
  Type: Reporting
  ID: Metrics
  Description: Reporting Metrics Data
  Priority: 1
steps:
  # lWorkflows is a named list of metric workflows.
  - output: Reporting_Metrics
    name: MakeMetric
    params:
      lWorkflows: lWorkflows
```

So we need to make sure that as a param lWorkflows is going to be passed:

```
metrics_wf <- gsm::MakeWorkflowList(strPath = 'workflow/2_metrics', strPackage = NULL)
# ... some other things to collect other reporting workflow components like the analysis data 
lReportingData <- gsm::RunWorkflows(
  reporting_wf,
  lData = c(lMappedData, list(lAnalyzed = analysis_grouped_data,
                              lWorkflows = metrics_wf)),
  lConfig = Reporting_lConfig
)
```

**Comment by samussiah** [comment]
@dpastoor - calling `MakeWorkflowList` as a step in the `Metrics` workflow is all that's needed here to pull in `lWorkflows` directly.

```
meta:
  Type: Reporting
  ID: Metrics
  Description: Reporting Metrics Data 
  Priority: 1
steps:
  # lWorkflows is a named list of metric workflows.
  - output: lWorkflows
    name: MakeWorkflowList
    params:
      strPath: workflows/2_metrics # path to metric workflow files
      strPackage: null
  - output: Reporting_Metrics
    name: MakeMetric
    params:
      lWorkflows: lWorkflows
```
