### ISSUE TITLE
QC: Qualification tests for `v1.4.0`

### ISSUE THREAD

**Issue by mattroumaya** [Gilead-BioStats/gsm#869]
Assessments and functionality to qualify for the `v1.4.0` release: 

1. For `AE_Assess()`, `Disp_Assess()`, `LB_Assess()`, and `PD_Assess()`, qualify valid output using the normal approximation method (`strMethod = "NormalApprox"`). 

Process: 

- Update specs for all assessments listed above. Example found [here](https://github.com/Gilead-BioStats/gsm/blob/dev/inst/qualification/spec_AE_Assess.yaml). 
- Proposed update: 
```yaml
- ID: S1_3
  Description: Given correct input data an X Event assessment can be done using the normal approximation method
  Risk: High
  Impact: High
  Tests:
    - TX_X
    - TX_X
```
- May need to reconfigure/renumber specs to group intended functionality for each statistical method at the top to be consistent
- Create relevant tests and place [here](https://github.com/Gilead-BioStats/gsm/tree/dev/tests/testqualification/qualification)
  - Recommendation to include a new function in the [`helper-qualification.R` file](https://github.com/Gilead-BioStats/gsm/blob/dev/tests/testqualification/qualification/helper-qualification.R) for `qualification_analyze_normalapprox()` and `qualification_flag_normalapprox()`. 

**More to be added after qualification discussion.**
